name = "FunctionAssertions"
uuid = "0a08f72c-ffa0-4fc9-a136-f81a86533b7f"
authors = ["Nathan Daly <nathan.daly@relational.ai> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
